### Vérifier que le backend fonctionne
GET http://localhost:5000/api/health

### Connexion - identifiants corrects
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin-create@test.fr",
    "password": "MotDePasse123"
}


### Connexion - mauvais mot de passe
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "password": "MauvaisMotDePasse!"
}


### Connexion - e-mail inexistant
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "inexistant@projet-spe4.fr",
    "password": "MotDePasse123!"
}

### Connexion - compte bloqué
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "password": "MotDePasse123!"
}

### Accéder au profil - sans token
GET http://localhost:5000/api/auth/me


### Accéder au profil - avec token
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTQ0NzQ4NiwiZXhwIjoxNzkxNDQ3Nzg2fQ.mH9BWr3HG5llOCwml75LGAYwuBn166f7IbtV_fIyv1k

### Modifier le profil
PUT http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM2Mjc0NSwiZXhwIjoxNzkxMzY2MzQ1fQ.NXWcBNdkhnqGGWxOCVoF6bnyjRa5rFMgNovi5adD24M
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "firstName": "Alban",
    "lastName": "Modifie"
}

### Modifier le mot de passe
PUT http://localhost:5000/api/auth/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTM3OTc0MiwiZXhwIjoxNzkxMzgwMDQyfQ.B-4938gMHpdPMn9_XZEdQjciblNkGfbTeB1l1vWNMto
Content-Type: application/json

{
    "currentPassword": "NouveauMotDePasse789!",
    "newPassword": "NouveauMotDePasse101112!"
}

### Préparer la 2FA
POST http://localhost:5000/api/auth/2fa/setup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM2NzQxMywiZXhwIjoxNzkxMzcxMDEzfQ.gpPiJ6Z4BsjJ2A5vGQQySZba82SFqEOjhMutuOG5qaw

### Vérifier le code 2FA
POST http://localhost:5000/api/auth/2fa/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM3ODU3MywiZXhwIjoxNzkxMzgyMTczfQ.vZ8fbEHnFjGShnImLB3OQwDH__2BtjTKbARCj7HgvxY
Content-Type: application/json

{
    "code": "831721"
}


### Validation du 2FA lors de la connexion
POST http://localhost:5000/api/auth/2fa/login
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTM3OTAzNiwiZXhwIjoxNzkxMzc5MzM2fQ.sbDTPpEckm8glFr3ETaLN71pruHdwWmD_Aq79ayQA0I",
    "code": "540712"
}

### Connexion - accès administrateur
GET http://localhost:5000/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTQ0NzkxOCwiZXhwIjoxNzkxNDQ4MjE4fQ.epiGAtyW2Paubf-MZs5wY3xCZUZxLMEb996vskioQts

### Bloquer l'utilisateur
PUT http://localhost:5000/api/admin/users/3/block
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTQ0NzkxOCwiZXhwIjoxNzkxNDQ4MjE4fQ.epiGAtyW2Paubf-MZs5wY3xCZUZxLMEb996vskioQts
Content-Type: application/json

{
    "isBlocked": true
}

### Débloquer l'utilisateur
PUT http://localhost:5000/api/admin/users/3/block
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTQ0NzkxOCwiZXhwIjoxNzkxNDQ4MjE4fQ.epiGAtyW2Paubf-MZs5wY3xCZUZxLMEb996vskioQts
Content-Type: application/json

{
    "isBlocked": false
}

### Passer en administrateur
PUT http://localhost:5000/api/admin/users/3/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTQ0ODM1NiwiZXhwIjoxNzkxNDQ4NjU2fQ.9-BN20bSCEKVE7BIt2MGAJT5EAnFlLUd6GgSep_8kwY
Content-Type: application/json

{
    "role": "ADMIN"
}

### Repasser en utilisateur
PUT http://localhost:5000/api/admin/users/3/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTQ0ODM1NiwiZXhwIjoxNzkxNDQ4NjU2fQ.9-BN20bSCEKVE7BIt2MGAJT5EAnFlLUd6GgSep_8kwY
Content-Type: application/json

{
    "role": "USER"
}

### Création d'un compte par un administrateur
POST http://localhost:5000/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc5MTQ0OTIxMSwiZXhwIjoxNzkxNDUyODExfQ.HN_YzwzVLlxNvSaPLKZwfPGohzwLVcef7TkNwWPD8ss
Content-Type: application/json

{
    "email": "admin-create@test.fr",
    "password": "MotDePasse123",
    "firstName": "Compte",
    "lastName": "Admin"
}

### Déconnexion
POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM2Mjc0NSwiZXhwIjoxNzkxMzY2MzQ1fQ.NXWcBNdkhnqGGWxOCVoF6bnyjRa5rFMgNovi5adD24M
