### Vérifier que le backend fonctionne
GET http://localhost:5000/api/health


### Inscription - nouvel utilisateur
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test3@projet-spe4.fr",
    "password": "MotDePasse789!",
    "firstName": "Pierre",
    "lastName": "Test"
}


### Inscription - adresse e-mail déjà utilisée
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "password": "NouveauMotDePasse123!",
    "firstName": "Autre",
    "lastName": "Test"
}

### Inscription - champs obligatoires
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test4@projet-spe4.fr",
    "password": "",
    "firstName": "Test",
    "lastName": "Validation"
}

### Inscription - e-mail invalide
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "email-invalide",
    "password": "MotDePasse123!",
    "firstName": "Test",
    "lastName": "Validation"
}

### Inscription - mot de passe trop court
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test5@projet-spe4.fr",
    "password": "1234567",
    "firstName": "Test",
    "lastName": "Validation"
}

### Inscription - prénom vide
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test6@projet-spe4.fr",
    "password": "MotDePasse123!",
    "firstName": "   ",
    "lastName": "Validation"
}

### Connexion - identifiants corrects
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "password": "NouveauMotDePasse101112!"
}


### Connexion - mauvais mot de passe
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "password": "MauvaisMotDePasse!"
}


### Connexion - e-mail inexistant
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "inexistant@projet-spe4.fr",
    "password": "MotDePasse123!"
}

### Connexion - compte bloqué
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "password": "MotDePasse123!"
}

### Accéder au profil - sans token
GET http://localhost:5000/api/auth/me


### Accéder au profil - avec token
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTM4MDI4MiwiZXhwIjoxNzkxMzgwNTgyfQ.KAcRy9D_QNcpcBm3YdSOwJLI0mb7_si3LTWIkGvzDas

### Modifier le profil
PUT http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM2Mjc0NSwiZXhwIjoxNzkxMzY2MzQ1fQ.NXWcBNdkhnqGGWxOCVoF6bnyjRa5rFMgNovi5adD24M
Content-Type: application/json

{
    "email": "test@projet-spe4.fr",
    "firstName": "Alban",
    "lastName": "Modifie"
}

### Modifier le mot de passe
PUT http://localhost:5000/api/auth/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTM3OTc0MiwiZXhwIjoxNzkxMzgwMDQyfQ.B-4938gMHpdPMn9_XZEdQjciblNkGfbTeB1l1vWNMto
Content-Type: application/json

{
    "currentPassword": "NouveauMotDePasse789!",
    "newPassword": "NouveauMotDePasse101112!"
}

### Préparer la 2FA
POST http://localhost:5000/api/auth/2fa/setup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM2NzQxMywiZXhwIjoxNzkxMzcxMDEzfQ.gpPiJ6Z4BsjJ2A5vGQQySZba82SFqEOjhMutuOG5qaw

### Vérifier le code 2FA
POST http://localhost:5000/api/auth/2fa/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM3ODU3MywiZXhwIjoxNzkxMzgyMTczfQ.vZ8fbEHnFjGShnImLB3OQwDH__2BtjTKbARCj7HgvxY
Content-Type: application/json

{
    "code": "831721"
}


### Validation du 2FA lors de la connexion
POST http://localhost:5000/api/auth/2fa/login
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR3b0ZhY3RvclBlbmRpbmciOnRydWUsImlhdCI6MTc5MTM3OTAzNiwiZXhwIjoxNzkxMzc5MzM2fQ.sbDTPpEckm8glFr3ETaLN71pruHdwWmD_Aq79ayQA0I",
    "code": "540712"
}

### Déconnexion
POST http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc5MTM2Mjc0NSwiZXhwIjoxNzkxMzY2MzQ1fQ.NXWcBNdkhnqGGWxOCVoF6bnyjRa5rFMgNovi5adD24M
